spring:
  rabbitmq:
    host: 172.17.91.21
    port: 5672
    username: alet
    password: alet
  data:
    redis:
      port: 6379
      host: 172.17.91.20
      username: default
  jackson:
    serialization:
      write-dates-as-timestamps: false